apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flux
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flux
  template:
    metadata:
      labels:
        app: hello-flux
    spec:
      containers:
      - name: hello-flux
        image: kicbase/echo-server:1.0
        ports:
        - containerPort: 8080
